version: 0.2
phases:
  build:
    commands:
      - npm install
      - npm run build
      - aws --version
      - aws s3 sync dist/ s3://build-output-20230309
# artifacts:
#   files:
#     - "dist/**/*"